# Site settings
title: min livsstil
email: huwung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  不用在意這個界面上的陌生單詞們；
  我把在使用的軟件或者方法學進行了綜述，可能需要一些專業知識背景，學習曲線或許會比較陡峭；
  我們實驗室正在走向計算健康科學，歡迎志同道合的Geek或者學霸。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huwung.github.io" # the base hostname & protocol for your site
twitter_username:  huWUNGplus
github_username:  huwung

# Build settings
markdown: kramdown
