<<<<<<< HEAD
permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

baseurl: "" # change to empty string ""
domain_name:
google_analytics:

source:      source
destination: _site

cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Hugo Hoover
title: Hugo Hoover | Desenvolvimento Web e tudo mais..
description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_description: "Desenvolvedor Front-end/Wordpress, Design Responsivo, HTML5, CSS3 e JavaScript"
meta_keywords: "site, website, loja virtual, lojas virtuais, e-commerce, wordpress, frontend, front-end, html5, css3, javascript, jquery, seo, otimizacao, performance"
url:
production_url:
repo:
disqus_shortname: hugohoover
rss_path: source/
author:
  name      : Hugo Bernstein
  image     : /assets/images/logo.derTiger.jpg
  email     : nandomoreira.me@gmail.com
  url       : http://nandomoreira.me
  facebook  : http://facebook.com/fernando.dev
  twitter   : http://twitter.com/nandomoreirame
  instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/nandomoreirame
  linkedin  : http://linkedin.com/in/nandomoreirame
  bio       : "Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."

# thought
thought:
  text: I have no special talent. I am only passionately curious.
  author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
=======
<<<<<<< HEAD
# Site settings
title: fenomen
email: huwung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  不用在意這個界面上的陌生單詞們；
  我把在使用的軟件或者方法學進行了綜述，可能需要一些專業知識背景，學習曲線或許會比較陡峭；
  我們實驗室正在走向計算健康科學，歡迎志同道合的Geek或者學霸。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://huwung.github.io" # the base hostname & protocol for your site
twitter_username:  huWUNGplus
github_username:  huwung

# Build settings
markdown: kramdown
=======
# Dependencies
markdown:	redcarpet
highlighter: pygments
permalink: pretty
paginate:	5

# Permalinks
permalink:	/blog/:title

# Setup
title:		Fenomen | 現象
tagline:	'blog'
description:	'My personal blog.'
url:		http://camporez.com

author:
  name:		'Hugo Hoover'
  url:


# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/huWANGplus
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/huwung
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/
    desc:	Add me on google+

  - icon:	feed
    url:	http://camporez.com/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	molnplus
  url:		http://molnplus.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

gems: [jekyll-paginate]
>>>>>>> b1c4c8c8f6ae34090bcd6553ea1180e36fdde351
>>>>>>> 6fd03eacbd752657087dff859c27e0b03e1cbc6d
